name: Postman

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

env:
  FORCE_COLOR : 'true' # Force colors in console output
  VERSION: "8.1.0"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix: 
        include:
          - os_name: 'Linux x86_64'
            os_type:  'linux64'
            extract_cmd: 'tar -xf'
            extension: '.tar.gz'
            
          - os_name: 'Mac OS'
            os_type:  'osx'
            extract_cmd: 'unzip -q'
            extension: '.zip'
    
    name: "Fix Postman Scratchpad - ${{ matrix.os_name }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name : "Install aria2 downloader" 
        run: sudo apt update && sudo apt install aria2
        
      - name : "Download & Extract Postman " 
        run: |
          aria2c -q "https://dl.pstmn.io/download/version/${{ env.VERSION }}/${{ matrix.os_type }}"
          ${{ matrix.extract_cmd }} Postman*
          
      - name : "Get Postman Version" 
        run: |
          ext=${{ matrix.extension }}
          file=$(ls Postman*${ext})
          version=$(python3 -c "import re; print(re.match(r'Postman.*(([0-9]+\.){2}[0-9]+)${ext}', '${file}').group(1))")
          echo "Postman Version = ${version}"
          echo "VERSION=${version}" >> $GITHUB_ENV
          rm -v ${file}
        
      - name : "Export POSTMAN_INSTALL_DIR Environment Variable" 
        run: |
          postman_install_dir=$PWD/$(ls -d Postman*)
          echo "Postman Install Directory path: ${postman_install_dir}"
          echo "POSTMAN_INSTALL_DIR=${postman_install_dir}" >> $GITHUB_ENV
          
      - name : "Fix Scratch Pad Banner" 
        run: |
          npm install
          npm run fix ${{ env.POSTMAN_INSTALL_DIR }}

      - name : "Create Postman archive" 
        run: |
          tar --xz -cf Postman-${{ matrix.os_type }}-${{ env.VERSION }}.tar.xz ./Postman*
          ls -lh
          
      - name : "Calculate Checksum" 
        run: |
          echo -e "\nChecksum - ${{ matrix.os_name }}\n" >> checksum
          echo -n "SHA1: " >> checksum
          sha1sum Postman*.tar.xz >> checksum
          echo -n "SHA256: " >> checksum
          sha256sum Postman*.tar.xz >> checksum

      - name: Release Files
        uses: softprops/action-gh-release@v1
        with:
          name: "Postman v${{ env.VERSION }}"
          body_path: checksum
          tag_name: ${{ env.VERSION }}
          files: Postman*.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

